import type { Book, Suggestion, MarketData } from '@/types'

export const DEMO_BOOKS: Book[] = [
  {
    id: 'demo-1',
    title: 'Il Nome della Rosa',
    author: 'Umberto Eco',
    isbn: '978-88-452-9058-0',
    publisher: 'Bompiani',
    year: 1980,
    cover: 'https://covers.openlibrary.org/b/isbn/9788845290580-L.jpg',
    summary: 'Un capolavoro del romanzo storico ambientato in un monastero medievale del 1327. Il frate francescano Guglielmo da Baskerville e il novizio Adso da Melk investigano una serie di misteriose morti tra i monaci. Un thriller medievale che intreccia filosofia, semiotica e avventura.',
    emotions: ['misterioso', 'riflessivo', 'avvincente', 'storico'],
    rating: 5,
    status: 'read',
    purchasePrice: 8.5,
    genre: 'Romanzo storico',
    pages: 502,
    language: 'it',
    marketData: {
      min: 8,
      max: 45,
      avg: 18,
      currency: 'EUR',
      lastUpdated: new Date().toISOString(),
      sources: [
        { platform: 'eBay', price: 12, condition: 'Buono' },
        { platform: 'Catawiki', price: 45, condition: 'Prima edizione' },
        { platform: 'Vinted', price: 8, condition: 'Accettabile' },
      ]
    },
    createdAt: new Date('2024-03-15').toISOString(),
    updatedAt: new Date('2024-03-15').toISOString(),
  },
  {
    id: 'demo-2',
    title: 'Se questo è un uomo',
    author: 'Primo Levi',
    isbn: '978-88-06-19350-0',
    publisher: 'Einaudi',
    year: 1947,
    cover: 'https://covers.openlibrary.org/b/isbn/9788806193500-L.jpg',
    summary: 'Testimonianza autobiografica della deportazione di Primo Levi ad Auschwitz. Un documento essenziale sulla Shoah, scritto con lucidità scientifica e profonda umanità. Un libro che ogni essere umano dovrebbe leggere almeno una volta nella vita.',
    emotions: ['commovente', 'profondo', 'malinconico', 'riflessivo'],
    rating: 5,
    status: 'read',
    purchasePrice: 12,
    genre: 'Autobiografia',
    pages: 219,
    language: 'it',
    marketData: {
      min: 10,
      max: 120,
      avg: 30,
      currency: 'EUR',
      lastUpdated: new Date().toISOString(),
      sources: [
        { platform: 'eBay', price: 15, condition: 'Buono' },
        { platform: 'Catawiki', price: 120, condition: 'Prima edizione 1947' },
        { platform: 'Subito', price: 10, condition: 'Usato' },
      ]
    },
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'demo-3',
    title: 'Il Gattopardo',
    author: 'Giuseppe Tomasi di Lampedusa',
    isbn: '978-88-07-81361-0',
    publisher: 'Feltrinelli',
    year: 1958,
    cover: 'https://covers.openlibrary.org/b/isbn/9788807813610-L.jpg',
    summary: 'Il romanzo racconta il declino dell\'aristocrazia siciliana attraverso gli occhi del Principe Fabrizio Salina durante il Risorgimento. Un affresco malinconico e magnifico di un\'epoca che tramonta, celebre per la frase "Bisogna che tutto cambi, perché tutto rimanga com\'era".',
    emotions: ['malinconico', 'storico', 'profondo', 'romantico'],
    rating: 5,
    status: 'read',
    purchasePrice: 14,
    genre: 'Romanzo',
    pages: 302,
    language: 'it',
    marketData: {
      min: 12,
      max: 200,
      avg: 35,
      currency: 'EUR',
      lastUpdated: new Date().toISOString(),
      sources: [
        { platform: 'eBay', price: 20, condition: 'Molto buono' },
        { platform: 'Catawiki', price: 200, condition: 'Prima edizione 1958' },
        { platform: 'Vinted', price: 12, condition: 'Usato' },
      ]
    },
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'demo-4',
    title: 'Gomorra',
    author: 'Roberto Saviano',
    isbn: '978-88-04-55297-4',
    publisher: 'Mondadori',
    year: 2006,
    cover: 'https://covers.openlibrary.org/b/isbn/9788804552974-L.jpg',
    summary: 'Un\'inchiesta-romanzo sull\'impero della camorra napoletana. Saviano svela il sistema Camorra con occhi di chi ha vissuto dall\'interno i meccanismi del crimine organizzato. Un libro che ha cambiato la vita dell\'autore e ha scosso l\'Italia.',
    emotions: ['inquietante', 'avvincente', 'profondo'],
    rating: 4,
    status: 'read',
    purchasePrice: 9,
    genre: 'Narrativa di non-fiction',
    pages: 331,
    language: 'it',
    marketData: {
      min: 5,
      max: 25,
      avg: 10,
      currency: 'EUR',
      lastUpdated: new Date().toISOString(),
      sources: [
        { platform: 'eBay', price: 8, condition: 'Buono' },
        { platform: 'Vinted', price: 5, condition: 'Usato' },
        { platform: 'Subito', price: 7, condition: 'Usato' },
      ]
    },
    createdAt: new Date('2023-12-05').toISOString(),
    updatedAt: new Date('2023-12-05').toISOString(),
  },
  {
    id: 'demo-5',
    title: 'La solitudine dei numeri primi',
    author: 'Paolo Giordano',
    isbn: '978-88-04-57457-0',
    publisher: 'Mondadori',
    year: 2008,
    cover: 'https://covers.openlibrary.org/b/isbn/9788804574570-L.jpg',
    summary: 'Due solitudini parallele che si sfiorano senza mai toccarsi davvero, come i numeri primi gemelli. Alice e Mattia crescono in mondi separati, uniti da cicatrici invisibili. Un romanzo delicato sulla solitudine, l\'amicizia e l\'amore impossibile.',
    emotions: ['malinconico', 'romantico', 'commovente', 'riflessivo'],
    rating: 4,
    status: 'reading',
    purchasePrice: 11,
    genre: 'Romanzo',
    pages: 261,
    language: 'it',
    marketData: {
      min: 5,
      max: 20,
      avg: 9,
      currency: 'EUR',
      lastUpdated: new Date().toISOString(),
      sources: [
        { platform: 'eBay', price: 7, condition: 'Buono' },
        { platform: 'Vinted', price: 5, condition: 'Usato' },
      ]
    },
    createdAt: new Date('2024-04-01').toISOString(),
    updatedAt: new Date('2024-04-01').toISOString(),
  },
]

export const DEMO_SUGGESTIONS: Suggestion[] = [
  {
    title: 'Il Processo',
    author: 'Franz Kafka',
    reason: 'Per la tua passione per romanzi con atmosfere misteriose e inquietanti, come Il Nome della Rosa',
    matchScore: 94,
    isbn: '978-88-452-9139-6',
    year: 1925,
    genre: 'Romanzo',
    cover: 'https://covers.openlibrary.org/b/isbn/9788845291396-L.jpg',
  },
  {
    title: 'Cent\'anni di solitudine',
    author: 'Gabriel García Márquez',
    reason: 'La profondità narrativa e il senso del tempo storico che ami nel Gattopardo, amplificati al massimo',
    matchScore: 91,
    isbn: '978-88-04-39710-7',
    year: 1967,
    genre: 'Romanzo magico',
    cover: 'https://covers.openlibrary.org/b/isbn/9788804397107-L.jpg',
  },
  {
    title: 'Midnight in the Garden of Good and Evil',
    author: 'John Berendt',
    reason: 'Come Gomorra, ma ambientato nel Sud degli Stati Uniti: un true crime che leggi come un romanzo',
    matchScore: 87,
    isbn: '978-0-679-75152-6',
    year: 1994,
    genre: 'True crime',
  },
  {
    title: 'La coscienza di Zeno',
    author: 'Italo Svevo',
    reason: 'Profondità psicologica e ironia come in Gomorra, ma in chiave completamente diversa',
    matchScore: 85,
    isbn: '978-88-11-36361-7',
    year: 1923,
    genre: 'Romanzo',
    cover: 'https://covers.openlibrary.org/b/isbn/9788811363617-L.jpg',
  },
]

export function getDemoMarketData(bookId: string): MarketData {
  const book = DEMO_BOOKS.find(b => b.id === bookId)
  if (book?.marketData) return book.marketData
  return {
    min: 8,
    max: 35,
    avg: 15,
    currency: 'EUR',
    lastUpdated: new Date().toISOString(),
    sources: [
      { platform: 'eBay', price: 12, condition: 'Buono' },
      { platform: 'Vinted', price: 8, condition: 'Usato' },
      { platform: 'Subito', price: 10, condition: 'Usato' },
    ]
  }
}
